set_property PACKAGE_PIN E3 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]

set_property IOSTANDARD LVCMOS33 [get_ports {RGB0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADDR[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADDR[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADDR[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADDR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADDR[0]}]
set_property PACKAGE_PIN G17 [get_ports {ADDR[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLOCK_O]
set_property PACKAGE_PIN H16 [get_ports OE]
set_property IOSTANDARD LVCMOS33 [get_ports LAT]
set_property IOSTANDARD LVCMOS33 [get_ports OE]

set_property PACKAGE_PIN G13 [get_ports CLOCK_O]
set_property PACKAGE_PIN E16 [get_ports {ADDR[0]}]
set_property PACKAGE_PIN F13 [get_ports {ADDR[2]}]



set_property PACKAGE_PIN E18 [get_ports {RGB1[1]}]
set_property PACKAGE_PIN G16 [get_ports LAT]
set_property PACKAGE_PIN D14 [get_ports {ADDR[1]}]
set_property PACKAGE_PIN F16 [get_ports {ADDR[3]}]
set_property PACKAGE_PIN C17 [get_ports {RGB0[1]}]
set_property PACKAGE_PIN D17 [get_ports {RGB0[2]}]
set_property PACKAGE_PIN G18 [get_ports {RGB1[0]}]
set_property PACKAGE_PIN F18 [get_ports {RGB1[2]}]
set_property PACKAGE_PIN E17 [get_ports {RGB0[0]}]
